### ISSUE TITLE
Sometimes scrollbars do not fade

### ISSUE THREAD

**Issue by Malmz** [xi-editor/druid#492] opened 2020-01-29 08:38 UTC
When leaving the widget from the side of the scrollbar it does not fade. reset_scrollbar_fade can only called from MouseMoved events. Fade should also be triggered when hot status changes to false.

An example of this can be seen in the list example.

**Comment by cmyr** [comment] 2020-01-30 02:49
yea, this is something to do with mouse event delivery when the mouse leaves the window. I'm really not sure exactly what's going on, but it's a bug, and I've seen it on multiple platforms so I think it's in druid somewhere.

**Comment by ForLoveOfCats** [comment] 2020-02-11 18:37
Continuing on https://github.com/xi-editor/druid/pull/539#issuecomment-584779175

I'm surprised to learn that the issue is no present on macOS, here it is reproduced on Linux with GTK
https://drive.google.com/open?id=1s7SoPurJbg7-Jsyl8YdHiln0f8RYWeZ2
(Sadly GH does not support video files)

**Comment by cmyr** [comment] 2020-02-11 18:44
yea just for illustration here is the behaiour on macos: 
![2020-02-11 13 43 28](https://user-images.githubusercontent.com/3330916/74267702-91bbc080-4cd4-11ea-9eea-f770ab5559df.gif)

**Comment by cmyr** [comment] 2020-02-11 19:21
fixed in #542

**Comment by cmyr** [comment] 2020-02-11 19:22
note: this does not fix the issue when the mouse is leaving the window on gtk; that is tracked by #541

**Closed by cmyr** 2020-02-11 19:21 UTC
Labels: bug

**Comment by ForLoveOfCats** [comment] 2020-02-11 19:25
Just to clarify for my own understanding, this is fixed as the original issue was between widgets which is why the out of window issue is separate yes?

**Comment by cmyr** [comment] 2020-02-11 19:30
This fixes the issue where, with events delivered correctly, we would fail to correctly handle an event that was exiting a scrollview, over the scrollbar.

The window issue is a fundamental issue around us not receiving necessary events from the platform.

Basically: with the platform behaving correctly, this bug is now fixed; now we just have some platform-specific stuff to resolve.
