### ISSUE TITLE
add {add, with}_children()

### ISSUE THREAD

**Issue by pythoneer** [xi-editor/druid#802] opened 2020-04-04 21:08 UTC
Coming from Flutter and really feel at home with the API from druid i would like to make a suggestion. It does not fundamentally improve anything but a pattern i use a lot in Flutter on Lists (and respectively on Column/Rows) is something like this.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MainWidget(),
    );
  }
}

class MainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const rawElements = ["one", "two", "tree", "four", "five", "six"];

    return Column(
      children: rawElements.map(createWidget),
    );
  }

  Widget createWidget(String elem) {
    return Padding(
      padding: const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
      child: Row(
        children: <Widget>[
          Padding(
            padding:
                const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
            child: Text(elem),
          ),
          Padding(
            padding:
                const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
            child: Text(elem.toUpperCase()),
          ),
        ],
      ),
    );
  }
}
```

the corresponding druid code would look like this

```rust
use druid::widget::{Container, Flex, Label, Padding, Scroll, SizedBox, Switch};
use druid::{AppLauncher, Color, LocalizedString, Widget, WidgetExt, WindowDesc};

fn build_app() -> impl Widget<()> {
    let raw_elements = vec!["one", "two", "tree", "four", "five", "six"];

    let mut col = Flex::column();

    for element in raw_elements {
        col.add_child(create_widget(element))
    }

    col
}

fn create_widget(elem: &str) -> impl Widget<()> {
    let mut row = Flex::row();
    row.add_child(Padding::new((20., 10.), Label::new(elem.clone())));
    row.add_child(Padding::new(
        (20., 10.),
        Label::new(elem.to_ascii_uppercase()),
    ));
    Padding::new((20., 10.), row)
}

fn main() {
    let main_window = WindowDesc::new(build_app)
        .title(LocalizedString::new("the-demo").with_placeholder("Things!"));
    let data = 0_u32;
    AppLauncher::with_window(main_window)
        .use_simple_logger()
        .launch(())
        .expect("launch failed");
}
```

I am aware that i can simplify the paddings with `WidgetExt` magic but that is of course not the point. The main Thing i want to highlight here is the usage of `children` in Flutter. The major advantage i see is that it does not "break" the definition and usage of the Colum/Rows apart from the rest of the code. In the Flutter example you have one "definition" of the layout you can read from "top to bottom". In the Druid case you need to "jump" visually.

Comparing
```dart
const rawElements = ["one", "two", "tree", "four", "five", "six"];

return Column(
  children: rawElements.map(createWidget),
);
```
and 

```rust
let raw_elements = vec!["one", "two", "tree", "four", "five", "six"];

let mut col = Flex::column();

for element in raw_elements {
    col.add_child(create_widget(element))
}

col
```
I think its getting clear what i mean. I want to emphasize that i am not speaking about lines of code. Imagine to have a little more complexity in it you cannot read this from top to bottom anymore to get an idea of how the layout is structured (and i really like to use map here :) )
I think the `make_widget` function makes it more clear. In the Flutter version i can basically "see" how the widget is laid out by reading it "top to bottom". In the Rust version

```rust
    let mut row = Flex::row();
    row.add_child(Padding::new((20., 10.), Label::new(elem.clone())));
    row.add_child(Padding::new(
        (20., 10.),
        Label::new(elem.to_ascii_uppercase()),
    ));
    Padding::new((20., 10.), row)
```

the topmost Widget (Padding) is the last element i am seeing. The row, that is in the middle of the widget tree is on top. One can imagine that with multiple rows/columns this can get confusing. For me the reason is the abundance or disability to add multiple children. 

In Flutter i have quite large blocks encapsulated in functions like `create_widget` witch are still easy to read because you don't need to jump around in the function visually to understand the structure of the widget tree that is being created and can read it from top to bottom. I feel like the way you currently have to construct `Flex` widgets is a little bit getting in the way – at least from my point of view – that could be absolutely wrong :)

Let me know what you think and if you are interested in such an addition and if its a good beginner issue so that i could possibly volunteer for it myself.  

EDIT: 
To make my goal a little bit more clear, this is what i have in mind.

```rust
use druid::widget::{Container, Flex, Label, Padding, Scroll, SizedBox, Switch};
use druid::{AppLauncher, Color, LocalizedString, Widget, WidgetExt, WindowDesc};

fn build_app() -> impl Widget<()> {
    let raw_elements = vec!["one", "two", "tree", "four", "five", "six"];
    Flex::column().add_children(raw_elements.into_iter().map(create_widget))
}

fn create_widget(elem: &str) -> impl Widget<()> {
    Padding::new(
        (20., 10.),
        Flex::row().add_children(vec![
            Padding::new((20., 10.), Label::new(elem.clone())),
            Padding::new((20., 10.), Label::new(elem.to_ascii_uppercase())),
        ]),
    )
}

fn main() {
    let main_window = WindowDesc::new(build_app)
        .title(LocalizedString::new("the-demo").with_placeholder("Things!"));
    let data = 0_u32;
    AppLauncher::with_window(main_window)
        .use_simple_logger()
        .launch(())
        .expect("launch failed");
}

```

**Comment by Finnerale** [comment] 2020-04-05 08:43
You could write it like this:
```rust
use druid::widget::{Flex, Label, Padding};
use druid::{AppLauncher, LocalizedString, Widget, WidgetExt, WindowDesc};

fn build_app() -> impl Widget<()> {
    let raw_elements = vec!["one", "two", "tree", "four", "five", "six"];

    raw_elements
        .iter()
        .fold(Flex::column(), |flex, e| flex.with_child(create_widget(e)))
}

fn create_widget(elem: &str) -> impl Widget<()> {
    let pad = (20., 10.);
    Flex::row()
        .with_child(Label::new(elem.clone()).padding(pad))
        .with_child(Label::new(elem.to_ascii_uppercase()).padding(pad))
        .padding(pad)
}

fn main() {
    let main_window = WindowDesc::new(build_app)
        .title(LocalizedString::new("the-demo").with_placeholder("Things!"));
    AppLauncher::with_window(main_window)
        .use_simple_logger()
        .launch(())
        .expect("launch failed");
}
```

**Comment by Finnerale** [comment] 2020-04-05 09:19
To elaborate a bit about why there is no `with_children`:
Such a method would need a signature like `with_children<W: Widget<T>>(self, impl Into<Iter<W>>)` but what is the type of `W` when you write
```rust
Flex::column()
  .with_children(vec![
    Label::new("a"),
    Padding::new(5., Label::new("b"))
  ])
```
Is it `Label` or `Padding`? (Such a `Vec` could not even be constructed)
So what you would have to write is
```rust
Flex::column()
  .with_children(vec![
    Label::new("a").boxed(),
    Padding::new(5., Label::new("b")).boxed()
  ])
```
To wrap all of them in `Box` as soon as there are two or more different types of widgets.
This is what Flutter (or rather Dart) does implicitly everywhere.
This is not necessary when chaining `with_child` though.

**Comment by pythoneer** [comment] 2020-04-05 09:42
Thanks @Finnerale for the suggestion. But as i mentioned my goal is not to decrease loc or use "fancy" ways to describe the layout. After revisiting my example i may have failed to get my point across. I was explicitly avoiding `WidgetExt` functionality like `.padding(..)` because those are exceptions, albeit very good ones. The "general case" how widgets in Flutter and hopefully in druid are "supposed" to be used is `WidgetA(WidgetB(WidgetC(...)))` where things like `*.padding(...)` are not available for all widgets especially not the ones i build myself (until i make them to behave like this)

The "problem" with your example is still the same, its hard to figure out the structure of the widget tree after reading the code. I think where my example failed is that it is a little bit to small because the example as it is right now is easy to comprehend on the first look. 

Please imagine to have those examples embedded into larger widget structures. If you gloss over a 100 lines snipped and see 
```
raw_elements
        .iter()
        .fold(Flex::column(), |flex, e| flex.with_child(create_widget(e)))
```
among other lines it is not very clear – at least for me – what the structure is in the end. I need to precess it for a while. But i can directly see that the Element i am getting from this line

```
Flex::column().add_children(raw_elements.into_iter().map(create_widget))
```
Is a column with `raw_elements` many things returned from `create_widget` without thinking about it, because i can just read it "top to bottom" (or in this case left to right) and know the structure. The same is the case with our other example. I admit, i failed to deliver an original example that would make this much clearer, because i don't wanted to create many other widgets and depend on the ones that are already available like padding.

I hope this example shows the problem a little bit better
```rust
    let first_level_sections = vec!["one", "two", "tree", "four", "five", "six"];
    let secons_level_sections = vec!["red", "blue", "yellow", "green", "pink", "orange"];

    Container::new(
        first_level_sections
            .iter()
            .fold(Flex::column(), |column, fls| {
                column.with_child(
                    secons_level_sections
                        .iter()
                        .fold(Flex::row(), |row, sls| row.with_child(create_widget(sls))),
                )
            }),
    )
```
It is very unclear how the structure would look like. You could "decompose" it like in my earlier example with explicit declarations and for loops but i think if it is written in this way

```rust
    let first_level_sections = vec!["one", "two", "tree", "four", "five", "six"];
    let secons_level_sections = vec!["red", "blue", "yellow", "green", "pink", "orange"];

    Container::new(Flex::column().add_children(
        first_level_sections.into_iter().map(|_fls| {
            Flex::row().add_children(secons_level_sections.into_iter.map(create_widget))
        }),
    ))
```
it is easier to see how the widget structure is in the end. 

EDIT: after your second comment.

Yeah i was also wondering about that, while preparing for a PR. I see that this is a problem that might make this unfeasible i just wanted to start a discussion about the "problem" in the first place – and maybe there is a better solution than `add_children`. My point is, yes you can build layouts with few lines of code, but the resulting code is harder to comprehend – in my opinion – because the order of the widgets you come across while reading the code does not correspond to the widget hierarchy anymore, opposed to the examples i tried to make. If it turns out that this is just a "bad idea" – because we cannot translate every pattern over from Flutter obviously – i am ok with it. There are many more even more major things that are not translatable. But this locked like a thing that would be possible and was one thing i directly noticed while comparing my Flutter layout structures to the ones i recreated with druid.

**Comment by pythoneer** [comment] 2020-04-05 09:55
One way could be to write it like this
```rust
    Container::new({
        let mut column = Flex::column();
        for _fls in first_level_sections {
            column.add_child({
                let mut row = Flex::row();
                for sls in &secons_level_sections {
                    row.add_child(create_widget(sls));
                }
                row
            })
        }
        column
    })
```
but i don't know if this is really helpful :P

**Comment by Finnerale** [comment] 2020-04-05 10:30
Maybe a practical example would be useful? I'm not sure right now for what you would actually have to iterate over a predefined, constant set of values?
Because that seems to me like the only true regression with Druid compared to Flutter.

Normal usages are pretty much the same after all
```dart
Padding(
  padding: const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
  child: Row(
    children: <Widget>[
      Padding(
        padding:
            const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
        child: Text(elem),
      ),
      Padding(
        padding:
           const EdgeInsets.only(left: 20, top: 10, right: 20, bottom: 10),
        child: Text(elem.toUpperCase()),
      ),
    ],
  ),
);
```
```rust
Padding::new(
    (20., 10.),
    Flex::row()
        .with_child(Padding::new(
            (20., 10.),
            Label::new(elem.clone())
        ))
        .with_child(Padding::new(
            (20., 10.),
            Label::new(elem.to_ascii_uppercase())
        ))
)
```

**Comment by pythoneer** [comment] 2020-04-05 10:32
Sorry for not explaining this :/ . The data is dynamically loaded at runtime e.g. from a webservice or the filesystem.

**Comment by Finnerale** [comment] 2020-04-05 10:38
Oh, in that case I doubt
```rust
Container::new({
    let mut column = Flex::column();
    for _fls in first_level_sections {
        column.add_child({
            let mut row = Flex::row();
            for sls in &secons_level_sections {
                row.add_child(create_widget(sls));
            }
            row
        })
    }
    column
})
```
is what you want to do? Because this would only create the widgets once but never update them when something changes.

Maybe you could use a [List](https://docs.rs/druid/0.5.0/druid/widget/struct.List.html) instead? Take a look at the [example](https://github.com/xi-editor/druid/blob/master/druid/examples/list.rs) as `List` currently is not really documented.

**Comment by pythoneer** [comment] 2020-04-05 10:50
I have to confess, that i haven't really worked with druid yet. I think i need to pause this conversation and start to just build something to get a better understanding of how things are supposed to work together, thus not wasting yours and others time. I just assumed that i could replace those constant arrays with the data from my model – but Lenses seems to be a very different kind of abstraction i am used to.

**Comment by Finnerale** [comment] 2020-04-05 11:01
The book at https://xi-editor.io/druid/ has improved quite a lot recently, maybe you want to take a look

**Comment by Finnerale** [comment] 2020-04-10 17:42
I'll close this Issue for now, should you still feel the need for this feel free to comment

**Closed by Finnerale** 2020-04-10 17:42 UTC
Labels: discussion

**Comment by cmyr** [comment] 2020-04-16 14:31
sorry to have missed this!

It does touch on one of the major differences between flutter and druid, which is that in druid you're explicitly responsible for updating your widget graph as needed.
